### ISSUE TITLE
Automatic updates automatically happening after installing dev builds.

### ISSUE THREAD

**Issue by Gernatch** [conan-io/conan-vs-extension#139]
If you open visual studio after immediately installing a dev build, it automatically updates to latest with prompt and then if you reopen visual studio in any case again it will have latest version.

**Comment by jgsogo** [comment]
(I'm not sure if I'm understanding the issue properly)

The command `conan install` is triggerend automatically when you open a solution with a Conan project, and by default it will update all the requirements. If this is not the desired behavior, there are some configuration options you can use:

![image](https://user-images.githubusercontent.com/1406456/61300606-91148780-a7e2-11e9-86d9-4a3d3a1e9fd3.png)

Setting "Update policy" to "False" will prevent the extension adding the `--update` parameter to the `conan install` call, so it won't download new versions/revisions from the remotes.

**Comment by kkripa84** [comment]
@jgsogo The issue here is after the installation of the extension.
If a user installs Conan extension (developer version) not from the Visual Studio Market place, then once the extension is installed, it automatically queues the extension to update to the latest version which is 1.1.134.

If the user re-opens the Visual Studio it would have already updated to version 1.1.134 already which is not needed by all users. 

NOTE: 
1. Automatic check for updates/extension is unchecked in Visual Studio settings.
2. If I uncheck Automatic updates for this extension option for Conan separately, still it gets into the queue for the update.

![image](https://user-images.githubusercontent.com/12863698/61306721-13895100-a7bb-11e9-9bf6-43a44da8efda.png)

3. I installed version: 1.0.166 from [here](https://ci.appveyor.com/project/ConanOrgCI/conan-vs-extension/builds/25773658/artifacts). 

It seems by default the extension is queued for updates to the latest version.

![image](https://user-images.githubusercontent.com/12863698/61306243-3ebf7080-a7ba-11e9-8f98-d03fa060ffd4.png)

**Comment by LBHawk** [comment]
This can be disabled in the Visual Studio settings -- I don't think this is an issue with the actual extension.  You can set the default behavior by navigating to:

Tools > Extensions & Updates > "Change your Extensions and Updates settings" > Uncheck "Automatically check for updates".

**Comment by kkripa84** [comment]
@LBHawk  as mentioned above in Note, it is already unchecked for all extensions Visual Studio settings. I will check if there is anything else missing. I was also not really sure if it is an issue with actual extension.

**Comment by kkripa84** [comment]
We noticed it looks okay with all settings unchecked as follows:

![image](https://user-images.githubusercontent.com/12863698/61309412-294d4500-a7c0-11e9-9428-a7d62f37abe1.png)

If only unchecked for "All user extensions", it still updates Conan Extension.

**Comment by jgsogo** [comment]
Hi, I think this has nothing to do with this extension, it's about how VS handles updates.

Googling I've found that you have to run VS as administrator (not being admin yourself, but "running as administrator") in order to see/change the value of the "Automatically update extensions" checkbox. Depending on how you have installed your extensions you can get more fine-grained control over updates.

**Comment by SSE4** [comment]
It's nothing to be done in the extension, we have no control over update policy, it's controlled only by Visual Studio settings.
