### ISSUE TITLE
Sign extention

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-vs-extension#37]
it would be nice to sign our extension, currently it's not signed and appears to be suspicious:
<img width="328" alt="_" src="https://user-images.githubusercontent.com/870236/54486457-2d716080-48bb-11e9-93bb-c482dca8d812.png">

**Comment by sboulema** [comment]
Info on signing vsix: https://docs.microsoft.com/en-us/visualstudio/extensibility/signing-vsix-packages?view=vs-2017

Selfplug - Azure devops Vsix Signing extension: https://github.com/sboulema/VsixTools

Looked into signing my extensions as well, but bailed on the idea because of pricy code signing certificates.

**Comment by solvingj** [comment]
thanks for the feedback, good to know. we might allocate budget for it when we get closer to release.

**Comment by jgsogo** [comment]
Ongoing effort here (https://github.com/conan-io/conan-vs-extension/pull/105), but not for v1.1.0
